//go:build ignore

package main

import (
	"bufio"
	"crypto/rand"
	"fmt"
	"math/bits"
	mrand "math/rand"
	"os"
	"time"
)

// Run: go run obfuscate.go && gofmt -s -w obfuscate_gen.go

func main() {
	strings := []struct {
		name string
		val  string
	}{
		// Server connection
		{"serverAddrObf", "5.78.188.169:9090"},
		{"hkdfSaltObf", "nrx-tcp-v1"},
		{"hkdfInfoObf", "aes256-gcm-key"},

		// Riot domain
		{"targetDomainObf", "clientconfig.rpg.riotgames.com"},

		// Process names (Windows)
		{"rcsExeObf", "RiotClientServices.exe"},
		{"rcuExeObf", "RiotClientUx.exe"},
		{"rcuRenderExeObf", "RiotClientUxRender.exe"},
		{"lcExeObf", "LeagueClient.exe"},
		{"lcuExeObf", "LeagueClientUx.exe"},
		{"lcuRenderExeObf", "LeagueClientUxRender.exe"},
		{"lolGameExeObf", "League of Legends.exe"},

		// Process names (macOS)
		{"rcsNameObf", "RiotClientServices"},
		{"rcuNameObf", "RiotClientUx"},
		{"lcNameObf", "LeagueClient"},
		{"lcuNameObf", "LeagueClientUx"},
		{"lolGameNameObf", "LeagueofLegends"},

		// Service names
		{"vgcServiceObf", "vgc"},
		{"vgkServiceObf", "vgk"},

		// Launch arguments
		{"patchlineLiveObf", "live"},
		{"productLoLObf", "league_of_legends"},
		{"disableFeatObf", "RendererCodeIntegrity"},

		// RCS finder
		{"rcsInstallsJsonObf", "RiotClientInstalls.json"},
		{"rcLiveKeyObf", "rc_live"},

		// macOS paths
		{"macRCSPathObf", "/Applications/Riot Client.app/Contents/MacOS/RiotClientServices"},

		// Vanguard config keys
		{"vgEnabledObf", "anticheat.vanguard.enabled"},
		{"vgBgInstallObf", "anticheat.vanguard.backgroundInstall"},
		{"lolVgEnabledObf", "lol.client_settings.vanguard.enabled"},
		{"lolVgEmbeddedObf", "lol.client_settings.vanguard.enabled_embedded"},
		{"lolVgUrlObf", "lol.client_settings.vanguard.url"},
		{"ksVgAttestObf", "keystone.client.feature_flags.vanguard_attestation.enabled"},
		{"ksVgLaunchDisabledObf", "keystone.client.feature_flags.vanguardLaunch.disabled"},
		{"ksRestartDisabledObf", "keystone.client.feature_flags.restart_required.disabled"},
		{"ksVgLaunchObf", "keystone.client.feature_flags.vanguardLaunch"},

		// Settings file
		{"riotSettingsFileObf", "RiotGamesPrivateSettings.yaml"},
	}

	// Generate random scrambler: 1 seed + 16 XOR keys + 16 ADD/SUB keys
	var scrambler [33]byte
	if _, err := rand.Read(scrambler[:]); err != nil {
		panic(err)
	}

	// Scramble processing order
	var order [16]int
	for i := range order {
		order[i] = i
	}
	rng := mrand.New(mrand.NewSource(time.Now().UnixNano()))
	rng.Shuffle(len(order), func(i, j int) { order[i], order[j] = order[j], order[i] })

	f, err := os.Create("obfuscate_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)
	defer w.Flush()

	w.WriteString("// Code generated by obfuscate.go DO NOT EDIT.\n\n")
	w.WriteString("package main\n\n")
	w.WriteString("import \"math/bits\"\n\n")

	// Write decode function
	w.WriteString("func decodeStr(obf []byte) string {\n")
	w.WriteString("\tret := make([]byte, len(obf))\n\tres := ret\n")
	fmt.Fprintf(w, "\tseed := byte(%d)\n", scrambler[0])
	w.WriteString("\tfor len(obf) > 0 {\n")

	xor := scrambler[1:17]
	add := scrambler[17:]
	for j, i := range order {
		if xor[i]%2 == 0 {
			fmt.Fprintf(w, "\t\tseed -= %d\n", add[i])
		} else {
			fmt.Fprintf(w, "\t\tseed += %d\n", add[i])
		}
		fmt.Fprintf(w, "\t\tif len(obf) >= %d {\n", i+1)
		fmt.Fprintf(w, "\t\t\tres[%d] = bits.RotateLeft8(obf[%d], %d) ^ %d ^ seed\n", i, i, -(-5 + j%10), xor[i])
		fmt.Fprintf(w, "\t\t\tseed ^= obf[%d]\n\t\t}\n", i)
	}
	w.WriteString("\t\tobf = obf[min(len(obf), 16):]\n")
	w.WriteString("\t\tres = res[min(len(res), 16):]\n\t}\n")
	w.WriteString("\treturn string(ret)\n}\n\n")

	// Write obfuscated string vars
	w.WriteString("var (\n")
	for _, s := range strings {
		obf := obfuscateKey([]byte(s.val), scrambler[0], xor, add, order)
		fmt.Fprintf(w, "\t%s = %#v\n", s.name, obf)
	}
	w.WriteString(")\n")

	fmt.Println("Generated obfuscate_gen.go")
}

func obfuscateKey(plain []byte, seed byte, xor []byte, add []byte, order [16]int) []byte {
	result := make([]byte, len(plain))
	recSeed := seed
	for j := range len(plain) + 16 {
		i := 16*(j/16) + order[j%16]

		if xor[i%16]%2 == 0 {
			seed -= add[i%16]
		} else {
			seed += add[i%16]
		}
		if xor[i%16]%2 == 0 {
			recSeed -= add[i%16]
		} else {
			recSeed += add[i%16]
		}
		if i >= len(plain) {
			continue
		}

		b := plain[i]
		result[i] = bits.RotateLeft8((b ^ xor[i%16] ^ seed), -5+(j%16)%10)
		seed ^= result[i]

		// Verify round-trip
		got := bits.RotateLeft8(result[i], -(-5+(j%16)%10)) ^ xor[i%16] ^ recSeed
		if got != b {
			panic(fmt.Sprintf("%d: got %d, want %d", i, got, b))
		}
		recSeed ^= result[i]
	}
	return result
}
