// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfigProfile(arg1) {
  return window['go']['main']['App']['ApplyConfigProfile'](arg1);
}

export function AutoAcceptQueue() {
  return window['go']['main']['App']['AutoAcceptQueue']();
}

export function ClaimRewards() {
  return window['go']['main']['App']['ClaimRewards']();
}

export function ClearLastError() {
  return window['go']['main']['App']['ClearLastError']();
}

export function ConcludeMatch() {
  return window['go']['main']['App']['ConcludeMatch']();
}

export function DismissPostGame() {
  return window['go']['main']['App']['DismissPostGame']();
}

export function DodgeLobby() {
  return window['go']['main']['App']['DodgeLobby']();
}

export function FindRCS() {
  return window['go']['main']['App']['FindRCS']();
}

export function GetActiveCriticalPrompt() {
  return window['go']['main']['App']['GetActiveCriticalPrompt']();
}

export function GetAutoConfigSyncStatus() {
  return window['go']['main']['App']['GetAutoConfigSyncStatus']();
}

export function GetChampSelectRule() {
  return window['go']['main']['App']['GetChampSelectRule']();
}

export function GetConfigProfiles() {
  return window['go']['main']['App']['GetConfigProfiles']();
}

export function GetInjectorEngines() {
  return window['go']['main']['App']['GetInjectorEngines']();
}

export function GetInjectorStatus() {
  return window['go']['main']['App']['GetInjectorStatus']();
}

export function GetKeepConfigOnAccountSwitch() {
  return window['go']['main']['App']['GetKeepConfigOnAccountSwitch']();
}

export function GetLastError() {
  return window['go']['main']['App']['GetLastError']();
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetLobbyScout() {
  return window['go']['main']['App']['GetLobbyScout']();
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function GetNoAccountI18n(arg1) {
  return window['go']['main']['App']['GetNoAccountI18n'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LaunchRiotClient() {
  return window['go']['main']['App']['LaunchRiotClient']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OnGameProcessExited(arg1, arg2, arg3) {
  return window['go']['main']['App']['OnGameProcessExited'](arg1, arg2, arg3);
}

export function PrepareLogin(arg1) {
  return window['go']['main']['App']['PrepareLogin'](arg1);
}

export function PurgeSystemTraces() {
  return window['go']['main']['App']['PurgeSystemTraces']();
}

export function ReconnectGame() {
  return window['go']['main']['App']['ReconnectGame']();
}

export function ResolveCriticalPrompt(arg1, arg2) {
  return window['go']['main']['App']['ResolveCriticalPrompt'](arg1, arg2);
}

export function SaveCurrentConfigProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveCurrentConfigProfile'](arg1, arg2);
}

export function SetAutoConfigSync(arg1, arg2) {
  return window['go']['main']['App']['SetAutoConfigSync'](arg1, arg2);
}

export function SetAutoInject(arg1) {
  return window['go']['main']['App']['SetAutoInject'](arg1);
}

export function SetChampSelectRule(arg1) {
  return window['go']['main']['App']['SetChampSelectRule'](arg1);
}

export function SetCustomLobbyStatus(arg1) {
  return window['go']['main']['App']['SetCustomLobbyStatus'](arg1);
}

export function SetInjectorEngine(arg1) {
  return window['go']['main']['App']['SetInjectorEngine'](arg1);
}

export function SetKeepConfigOnAccountSwitch(arg1) {
  return window['go']['main']['App']['SetKeepConfigOnAccountSwitch'](arg1);
}

export function SetRegaliaProfile(arg1, arg2) {
  return window['go']['main']['App']['SetRegaliaProfile'](arg1, arg2);
}

export function StartWorker() {
  return window['go']['main']['App']['StartWorker']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function StopAutoAccept() {
  return window['go']['main']['App']['StopAutoAccept']();
}

export function StopWorker() {
  return window['go']['main']['App']['StopWorker']();
}

export function ToggleConfigReadOnly(arg1) {
  return window['go']['main']['App']['ToggleConfigReadOnly'](arg1);
}

export function TriggerInject() {
  return window['go']['main']['App']['TriggerInject']();
}
