// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyConfigProfile(arg1:string):Promise<string>;

export function AutoAcceptQueue():Promise<string>;

export function ClaimRewards():Promise<Array<string>>;

export function ClearLastError():Promise<string>;

export function ConcludeMatch():Promise<string>;

export function DismissPostGame():Promise<string>;

export function DodgeLobby():Promise<string>;

export function FindRCS():Promise<string>;

export function GetActiveCriticalPrompt():Promise<main.CriticalPrompt>;

export function GetAutoConfigSyncStatus():Promise<Record<string, any>>;

export function GetChampSelectRule():Promise<main.ChampSelectRule>;

export function GetConfigProfiles():Promise<Array<main.ConfigProfileInfo>>;

export function GetInjectorEngines():Promise<Array<main.InjectorEngineInfo>>;

export function GetInjectorStatus():Promise<main.InjectorStatus>;

export function GetKeepConfigOnAccountSwitch():Promise<boolean>;

export function GetLastError():Promise<string>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetLobbyScout():Promise<main.LobbyScoutReport>;

export function GetLocale():Promise<string>;

export function GetNoAccountI18n(arg1:string):Promise<main.NoAccountI18n>;

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<string>;

export function LaunchRiotClient():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<string>;

export function OnGameProcessExited(arg1:Error,arg2:number,arg3:string):Promise<void>;

export function PrepareLogin(arg1:string):Promise<string>;

export function PurgeSystemTraces():Promise<string>;

export function ReconnectGame():Promise<string>;

export function ResolveCriticalPrompt(arg1:string,arg2:boolean):Promise<string>;

export function SaveCurrentConfigProfile(arg1:string,arg2:string):Promise<string>;

export function SetAutoConfigSync(arg1:boolean,arg2:string):Promise<string>;

export function SetAutoInject(arg1:boolean):Promise<string>;

export function SetChampSelectRule(arg1:main.ChampSelectRule):Promise<string>;

export function SetCustomLobbyStatus(arg1:string):Promise<string>;

export function SetInjectorEngine(arg1:string):Promise<string>;

export function SetKeepConfigOnAccountSwitch(arg1:boolean):Promise<string>;

export function SetRegaliaProfile(arg1:string,arg2:string):Promise<string>;

export function StartWorker():Promise<string>;

export function Stop():Promise<string>;

export function StopAutoAccept():Promise<string>;

export function StopWorker():Promise<string>;

export function ToggleConfigReadOnly(arg1:boolean):Promise<string>;

export function TriggerInject():Promise<string>;
